// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotorRegister.Infrastrucutre.Database;

#nullable disable

namespace MotorRegister.Infrastrucutre.Migrations
{
    [DbContext(typeof(MotorRegisterDbContext))]
    [Migration("20240808100301_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4");

            modelBuilder.Entity("MotorRegister.Core.Entities.InspectionResult", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleId", "Date");

                    b.ToTable("InspectionResults");
                });

            modelBuilder.Entity("MotorRegister.Core.Entities.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("InformationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegistrationStatusDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usage")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InformationId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("MotorRegister.Core.Entities.VehicleInformation", b =>
                {
                    b.Property<string>("ChassisNumber")
                        .HasColumnType("TEXT");

                    b.Property<short>("AxleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedFrom")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurbWeight")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstRegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAxleLoad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("TechnicalTotalWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalWeight")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TowingCapability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChassisNumber");

                    b.ToTable("VehicleInformations");
                });

            modelBuilder.Entity("MotorRegister.Core.Entities.InspectionResult", b =>
                {
                    b.HasOne("MotorRegister.Core.Entities.Vehicle", null)
                        .WithMany("InspectionResults")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotorRegister.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("MotorRegister.Core.Entities.VehicleInformation", "Information")
                        .WithMany()
                        .HasForeignKey("InformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Information");
                });

            modelBuilder.Entity("MotorRegister.Core.Entities.Vehicle", b =>
                {
                    b.Navigation("InspectionResults");
                });
#pragma warning restore 612, 618
        }
    }
}
